# Generated by Django 4.2.4 on 2023-08-08 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='hosts',
            new_name='host',
        ),
    ]
